name: HamsterBall
main: cn.hamster3.mc.plugin.ball.bukkit.HamsterBallPlugin
version: ${version}

author: MiniDay
website: https://github.com/MiniDay/hamster-ball
description: 仓鼠球：一个基于 Netty 的 Minecraft 服务端通用消息中间件（原HamsterService）

depend:
  - HamsterCore
