# 是否允许在控制台输出调试信息
debug: false

ball-server:
  host: "ball.hamster3.cn"
  port: 58888
  nio-thread: 10

server-info:
  # 服务器唯一识别码，最长 32 字符
  id: "BungeeCord"
  # 服务端名称，用于展示给玩家看
  name: "代理端"
  host: 0.0.0.0
  port: 25577
